server:
  servlet:
    context-path: /indoor-analytics

spring:
  application:
    name: indoor-analytics

springdoc:
  swagger-ui:
    enabled: true
    default-models-expand-depth: -1

management:
  endpoints:
    web:
      exposure:
        include: "metrics"